version: "3.3"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    networks:
      - app-network
    depends_on:
      - backend
    # command: sh -c "pnpm install && pnpm run dev"
    # env_file:
    #   - frontend/.env.local

# marumo追加分
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - 5000:5000
    networks:
      - app-network
    tty: true
    volumes: 
      - ./backend:/app

networks:
  app-network:
    driver: bridge